services:
  vaultwarden:
    image: vaultwarden/server:1.35.4-alpine
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - DOMAIN=https://vault.davidhebert.site
      - SIGNUPS_ALLOWED=true
    volumes:
      - ./vw-data/:/data/

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    depends_on:
      - vaultwarden