name: "selfhosted"
is_done_tick_dot_com: false
is_user_creation_disabled: false

database:
  type: "sqlite"
  migration: true

jwt:
  secret: "PASTE_YOUR_GENERATED_SECRET_HERE"
  session_time: 168h
  max_refresh: 1440h

server:
  port: 2021
  read_timeout: 10s
  write_timeout: 10s
  rate_period: 60s
  rate_limit: 300
  cors_allow_origins:
    - "https://todo.davidhebert.site"
    - "https://localhost"
    - "http://localhost"
    - "capacitor://localhost"
  serve_frontend: true
  public_host: "https://todo.davidhebert.site"

logging:
  level: "info"
  encoding: "json"
  development: false

scheduler_jobs:
  due_job: 30m
  overdue_job: 3h
  pre_due_job: 3h

realtime:
  enabled: true
  sse_enabled: true
  allowed_origins:
    - "https://todo.davidhebert.site"